- name: Update and upgrade apt packages
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Update cache and upgrade packages
      apt:
        update_cache: yes
        upgrade: yes          # or 'dist' for dist-upgrade
        cache_valid_time: 86400
