- name: Sample AWX Playbook for Ubuntu Servers
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 86400   # one day

    - name: Upgrade installed packages
      apt:
        upgrade: yes
